
project_id = "zlqzvvptrknyjexqzlpx"

[auth.email]
enable_confirmations = false
double_confirm_changes = true
enable_signup = true

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.hooks]
custom_access_token = ""

[realtime]
enabled = true
ip_address = "0.0.0.0"
port = 54327
max_concurrent_users = 200
pool_size = 4
pool_timeout = 3000
max_subscription_items_per_user = 1000
registered_listeners = ["postgres_changes"]
database_polling_interval_ms = 100
database_polling_timeout_ms = 1000

[functions]
function_timeout_seconds = 60

[functions.generate-collection-export]
verify_jwt = true
